### ISSUE TITLE
Getting NotSupported-error

### ISSUE THREAD

**Issue by Yukkun** [ShokoAnime/Shokofin#24]
Here is log of the things, " This error occurs when a plugin references an incompatible version of one of the shared libraries." seems to be the main issue with this

> [2022-06-20 14:12:02.286 +03:00] [INF] [1] Main: Jellyfin version: "10.8.0"
[2022-06-20 14:12:02.319 +03:00] [INF] [1] Main: Environment Variables: ["[JELLYFIN_LOG_DIR, F:\Programs\Jellyfin\Server\log]"]
[2022-06-20 14:12:02.327 +03:00] [INF] [1] Main: Arguments: ["C:\Program Files\Jellyfin\Server\jellyfin.dll", "--datadir", "F:\Programs\Jellyfin\Server"]
[2022-06-20 14:12:02.330 +03:00] [INF] [1] Main: Operating system: "Windows"
[2022-06-20 14:12:02.332 +03:00] [INF] [1] Main: Architecture: X64
[2022-06-20 14:12:02.337 +03:00] [INF] [1] Main: 64-Bit Process: True
[2022-06-20 14:12:02.338 +03:00] [INF] [1] Main: User Interactive: True
[2022-06-20 14:12:02.339 +03:00] [INF] [1] Main: Processor count: 4
[2022-06-20 14:12:02.340 +03:00] [INF] [1] Main: Program data path: "F:\Programs\Jellyfin\Server"
[2022-06-20 14:12:02.342 +03:00] [INF] [1] Main: Web resources path: "C:\Program Files\Jellyfin\Server\jellyfin-web"
[2022-06-20 14:12:02.343 +03:00] [INF] [1] Main: Application directory: "C:\Program Files\Jellyfin\Server\"
[2022-06-20 14:12:03.175 +03:00] [INF] [1] Emby.Server.Implementations.AppBase.BaseConfigurationManager: Setting cache path: "F:\Programs\Jellyfin\Server\cache"
[2022-06-20 14:12:03.673 +03:00] [INF] [1] Emby.Server.Implementations.ApplicationHost: Loading assemblies
[2022-06-20 14:12:05.113 +03:00] [ERR] [1] Emby.Server.Implementations.Plugins.PluginManager: Failed to load assembly "F:\Programs\Jellyfin\Server\plugins\Shoko_1.7.3.0\Shokofin.dll". This error occurs when a plugin references an incompatible version of one of the shared libraries. Disabling plugin.
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Method 'ExecuteAsync' in type 'Shokofin.Tasks.ExportUserDataTask' from assembly 'Shokofin, Version=1.7.3.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ExecuteAsync' in type 'Shokofin.Tasks.ImportUserDataTask' from assembly 'Shokofin, Version=1.7.3.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
Method 'ExecuteAsync' in type 'Shokofin.Tasks.SyncUserDataTask' from assembly 'Shokofin, Version=1.7.3.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Emby.Server.Implementations.Plugins.PluginManager.LoadAssemblies()+MoveNext()
System.TypeLoadException: Method 'ExecuteAsync' in type 'Shokofin.Tasks.ExportUserDataTask' from assembly 'Shokofin, Version=1.7.3.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ExecuteAsync' in type 'Shokofin.Tasks.ImportUserDataTask' from assembly 'Shokofin, Version=1.7.3.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
System.TypeLoadException: Method 'ExecuteAsync' in type 'Shokofin.Tasks.SyncUserDataTask' from assembly 'Shokofin, Version=1.7.3.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.
[2022-06-20 14:12:06.615 +03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN addresses : "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2022-06-20 14:12:06.618 +03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Defined LAN exclusions : "[]"
[2022-06-20 14:12:06.620 +03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using LAN addresses: "[10.0.0.0/8,172.16.0.0/12,192.168.0.0/16]"
[2022-06-20 14:12:06.645 +03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind addresses: "[]"
[2022-06-20 14:12:06.647 +03:00] [INF] [1] Jellyfin.Networking.Manager.NetworkManager: Using bind exclusions: "[]"
[2022-06-20 14:12:11.891 +03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "TMDb" "10.8.0.0"
[2022-06-20 14:12:11.894 +03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "Studio Images" "10.8.0.0"
[2022-06-20 14:12:11.897 +03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "OMDb" "10.8.0.0"
[2022-06-20 14:12:11.899 +03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "MusicBrainz" "10.8.0.0"
[2022-06-20 14:12:11.902 +03:00] [INF] [1] Emby.Server.Implementations.Plugins.PluginManager: Loaded plugin: "AudioDB" "10.8.0.0"

**Comment by revam** [comment]
Will be fixed at the same time as #23

**Comment by revam** [comment]
Since they're both related to the plugin not working on 10.8
