### ISSUE TITLE
unhandled exception scanning movies

### ISSUE THREAD

**Issue by t0815** [ShokoAnime/Shokofin#73]
### Jellyfin version.

10.9.11

### Shokofin version.

4.1.1.33 (dev)

### Shoko Server version, release channel, and commit hash.

4.2.2

### File structure of your _Media Library Folder in Jellyfin_/_Import Folder in Shoko Server_.

../Movies/<name>/<file>.xyz

### Screenshot of the "library settings" section of the plugin settings.

![grafik](https://github.com/user-attachments/assets/8b6bd258-bee0-41e7-88cc-94a101ac6844)

### Library Type(s).

Movies

### Do the issue persists after creating a library with Shoko set as the only metadata provider? (Now is your time to check if you haven't already.)

- [X] Yes, I hereby confirm that the issue persists after creating a library with Shoko set as the only metadata provider.

### Issue

When scanning Movies, an exception occurs. From what i can tell from exception message, its not directly a plugin-exception, but an error from shoko api. I did check shoko logs too, but no real details there. ill append shoko last log messages too.

### Stack Trace

``
[2024-09-11 18:13:26.845 +02:00] [INF] [33] Shokofin.Resolvers.ShokoIgnoreRule: Found shoko group "Goblin Slayer: Goblin's Crown" (Series="2756",ExtraSeries=[],Group="2253")
[2024-09-11 18:13:27.009 +02:00] [INF] [33] Shokofin.Resolvers.ShokoIgnoreRule: Found shoko group "Eiga Go-Toubun no Hanayome" (Series="3979",ExtraSeries=[],Group="3206")
[2024-09-11 18:13:27.270 +02:00] [INF] [33] Shokofin.Resolvers.ShokoIgnoreRule: Found show in movie library, ignoring shoko series. (Series="4275",ExtraSeries=[])
[2024-09-11 18:13:27.349 +02:00] [ERR] [33] Shokofin.Resolvers.ShokoIgnoreRule: Threw unexpectedly; "InternalServerErrorException"
Shokofin.API.Models.ApiException: InternalServerErrorException
   at Shokofin.API.ShokoAPIClient.<>c__DisplayClass19_0`1.<<Get>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Shokofin.Utils.GuardedMemoryCache.GetOrCreateAsync[TItem](Object key, Action`1 foundAction, Func`1 createFactory, MemoryCacheEntryOptions createOptions)
   at Shokofin.API.ShokoAPIClient.Get[ReturnType](String url, HttpMethod method, String apiKey, Boolean skipCache)
   at Shokofin.API.ShokoAPIManager.GetSeriesIdsForSeason(String seriesId)
   at Shokofin.API.ShokoAPIManager.GetSeriesIdForPath(String path)
   at Shokofin.API.ShokoAPIManager.GetSeasonInfoByPath(String path)
   at Shokofin.Resolvers.ShokoIgnoreRule.ShouldFilterDirectory(String partialPath, String fullPath, Nullable`1 collectionType, Boolean shouldIgnore)
   at Shokofin.Resolvers.ShokoIgnoreRule.ShouldFilterItem(Folder parent, FileSystemMetadata fileInfo)
[2024-09-11 18:13:27.366 +02:00] [ERR] [8] MediaBrowser.Controller.Entities.BaseItem: Error retrieving children
Shokofin.API.Models.ApiException: InternalServerErrorException
   at Shokofin.API.ShokoAPIClient.<>c__DisplayClass19_0`1.<<Get>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Shokofin.Utils.GuardedMemoryCache.GetOrCreateAsync[TItem](Object key, Action`1 foundAction, Func`1 createFactory, MemoryCacheEntryOptions createOptions)
   at Shokofin.API.ShokoAPIClient.Get[ReturnType](String url, HttpMethod method, String apiKey, Boolean skipCache)
   at Shokofin.API.ShokoAPIManager.GetSeriesIdsForSeason(String seriesId)
   at Shokofin.API.ShokoAPIManager.GetSeriesIdForPath(String path)
   at Shokofin.API.ShokoAPIManager.GetSeasonInfoByPath(String path)
   at Shokofin.Resolvers.ShokoIgnoreRule.ShouldFilterDirectory(String partialPath, String fullPath, Nullable`1 collectionType, Boolean shouldIgnore)
   at Shokofin.Resolvers.ShokoIgnoreRule.ShouldFilterItem(Folder parent, FileSystemMetadata fileInfo)
   at Shokofin.Resolvers.ShokoIgnoreRule.MediaBrowser.Controller.Resolvers.IResolverIgnoreRule.ShouldIgnore(FileSystemMetadata fileInfo, BaseItem parent)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Emby.Server.Implementations.Library.LibraryManager.IgnoreFile(FileSystemMetadata file, BaseItem parent)
   at Emby.Server.Implementations.Library.LibraryManager.<>c__DisplayClass87_0.<ResolvePaths>b__0(FileSystemMetadata i)
   at System.Linq.Enumerable.WhereArrayIterator`1.ToList()
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePaths(IEnumerable`1 files, IDirectoryService directoryService, Folder parent, LibraryOptions libraryOptions, Nullable`1 collectionType, IItemResolver[] resolvers)
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePaths(IEnumerable`1 files, IDirectoryService directoryService, Folder parent, LibraryOptions libraryOptions, Nullable`1 collectionType)
   at MediaBrowser.Controller.Entities.Folder.GetNonCachedChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
``

---
shoko log
---

2024-09-14 12:11:01
Info
Event '00000000000000000000000000000000' queued.
2024-09-14 12:11:01
Error
Connection id "0HN68D0I7DM9N", Request id "0HN68D0I7DM9N:00000007": An unhandled exception was thrown by the application.
2024-09-14 12:13:11
Info
Event '00000000000000000000000000000000' queued.
2024-09-14 12:13:11
Error
Connection id "0HN68D0I7DMB3", Request id "0HN68D0I7DMB3:00000113": An unhandled exception was thrown by the application.
2024-09-14 12:14:03
Info
Event '00000000000000000000000000000000' queued.
2024-09-14 12:14:03
Error
Connection id "0HN68D0I7DMBM", Request id "0HN68D0I7DMBM:00000003": An unhandled exception was thrown by the application.

**Comment by revam** [comment]
@t0815 enable trace logging in shoko server (from the web ui settings), then refresh the movie (goblin slayer: goblin's crown) or library in jellyfin and post the shoko server side stack trace when the error occurs.

**Comment by revam** [comment]
I'll assune this is related to isuue #61, just from another endpoint. But having the stack trace to confirm or reject my hypothesis would be nice.

**Comment by t0815** [comment]
```
[2024-09-14 14:39:15:424] Info|AsyncMethodBuilderCore.Start => <InvokeAsync>d__10.MoveNext => <>c__DisplayClass10_0.<InvokeAsync>g__CaptureException|4 Event '00000000000000000000000000000000' queued.
[2024-09-14 14:39:15:424] Error|ExecutionContext.RunFromThreadPoolDispatchLoop => <ProcessRequests>d__226`1.MoveNext => HttpProtocol.ReportApplicationError Connection id "0HN6KN6N2DVDT", Request id "0HN6KN6N2DVDT:00000114": An unhandled exception was thrown by the application.: System.NullReferenceException: Object reference not set to an instance of an object.
   at Shoko.Server.API.v3.Models.Shoko.Series.TvDB..ctor(HttpContext ctx, TvDB_Series tbdbSeries, SVR_AnimeSeries series, List`1 episodeList) in D:\a\ShokoServer\ShokoServer\Shoko.Server\API\v3\Models\Shoko\Series.cs:line 1037
   at Shoko.Server.API.v3.Models.Shoko.Series.<>c__DisplayClass52_0.<GetTvDBInfo>b__1(TvDB_Series tvdbSer) in D:\a\ShokoServer\ShokoServer\Shoko.Server\API\v3\Models\Shoko\Series.cs:line 470
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Shoko.Server.API.v3.Models.Shoko.Series..ctor(HttpContext ctx, SVR_AnimeSeries ser, Boolean randomiseImages, HashSet`1 includeDataFrom) in D:\a\ShokoServer\ShokoServer\Shoko.Server\API\v3\Models\Shoko\Series.cs:line 132
   at Shoko.Server.API.v3.Controllers.SeriesController.GetSeries(Int32 seriesID, Boolean randomImages, HashSet`1 includeDataFrom) in D:\a\ShokoServer\ShokoServer\Shoko.Server\API\v3\Controllers\SeriesController.cs:line 123
   at lambda_method1293(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Shoko.Server.API.APIExtensions.<>c.<<UseAPI>b__2_0>d.MoveNext() in D:\a\ShokoServer\ShokoServer\Shoko.Server\API\APIExtensions.cs:line 222
--- End of stack trace from previous location ---
   at Sentry.AspNetCore.SentryMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Sentry.AspNetCore.SentryMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)

```

**Comment by revam** [comment]
Looking at the stack trace from Shokofin then it seems like an error unrelated to this server side stack trace. The endpoints used in the functions where it threw in the stack trace from Shokofin doesn't contain any TvDB data, but the stack trace you posted for the server were for dehydrating TvDB data to send.

Were there any other errors in the log besides that one?

**Comment by t0815** [comment]
no, i did try again, and this error occurs at the same time:

```
[2024-09-14 16:14:03:204] Trace|AsyncMethodBuilderCore.Start => <InvokeAsync>d__10.MoveNext => <>c__DisplayClass10_0.<InvokeAsync>g__CaptureException|4 Sending event 'Sentry.SentryEvent' to Sentry.
[2024-09-14 16:14:03:204] Info|AsyncMethodBuilderCore.Start => <InvokeAsync>d__10.MoveNext => <>c__DisplayClass10_0.<InvokeAsync>g__CaptureException|4 Event '00000000000000000000000000000000' queued.
[2024-09-14 16:14:03:204] Error|ExecutionContext.RunFromThreadPoolDispatchLoop => <ProcessRequests>d__226`1.MoveNext => HttpProtocol.ReportApplicationError Connection id "0HN6KN6N2DVID", Request id "0HN6KN6N2DVID:00000114": An unhandled exception was thrown by the application.: System.NullReferenceException: Object reference not set to an instance of an object.
   at Shoko.Server.API.v3.Models.Shoko.Series.TvDB..ctor(HttpContext ctx, TvDB_Series tbdbSeries, SVR_AnimeSeries series, List`1 episodeList) in D:\a\ShokoServer\ShokoServer\Shoko.Server\API\v3\Models\Shoko\Series.cs:line 1029
   at Shoko.Server.API.v3.Models.Shoko.Series.<>c__DisplayClass52_0.<GetTvDBInfo>b__1(TvDB_Series tvdbSer) in D:\a\ShokoServer\ShokoServer\Shoko.Server\API\v3\Models\Shoko\Series.cs:line 470
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Shoko.Server.API.v3.Models.Shoko.Series..ctor(HttpContext ctx, SVR_AnimeSeries ser, Boolean randomiseImages, HashSet`1 includeDataFrom) in D:\a\ShokoServer\ShokoServer\Shoko.Server\API\v3\Models\Shoko\Series.cs:line 132
   at Shoko.Server.API.v3.Controllers.SeriesController.GetSeries(Int32 seriesID, Boolean randomImages, HashSet`1 includeDataFrom) in D:\a\ShokoServer\ShokoServer\Shoko.Server\API\v3\Controllers\SeriesController.cs:line 123
   at lambda_method1293(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Shoko.Server.API.APIExtensions.<>c.<<UseAPI>b__2_0>d.MoveNext() in D:\a\ShokoServer\ShokoServer\Shoko.Server\API\APIExtensions.cs:line 222
--- End of stack trace from previous location ---
   at Sentry.AspNetCore.SentryMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Sentry.AspNetCore.SentryMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
````

**Comment by t0815** [comment]
hmm. but why TVDb... strange, maybe a broken entry again?

**Comment by revam** [comment]
so i was looking at the wrong method earlier. so it seems possible that this is the error. sorry for that.

refresh or remove tvdb emtry for the shoko series in Shoko Desktop. that should fix it.

**Comment by revam** [comment]
> hmm. but why TVDb... strange, maybe a broken entry again?

probably. hard to say without investing.

**Comment by t0815** [comment]
ill try to remove the entry, and try again. ahtho, this one seems to be valid
https://thetvdb.com/series/the-quintessential-quintuplets/seasons/official/0

**Comment by t0815** [comment]
ok. removing does not change. And i noticed, the last series id does not match with the movie

```
[2024-09-14 16:30:57.506 +02:00] [INF] [41] Shokofin.Resolvers.ShokoIgnoreRule: Found shoko group "Eiga Go-Toubun no Hanayome" (Series="3979",ExtraSeries=[],Group="3206")
[2024-09-14 16:30:57.723 +02:00] [INF] [37] Shokofin.Resolvers.ShokoIgnoreRule: Found show in movie library, ignoring shoko series. (Series="4275",ExtraSeries=[])
```

i have to check Database to see, which series the id 4275 is...

**Comment by revam** [comment]
I can probably add an extra log point to log the guarded memory key when it throws.

**Comment by revam** [comment]
@t0815 can you update to `4.1.1.34` and rescan the library in jellyfin to see which series id is causing the error? take note that it may be one of the prequels or sequels to the series id in the log that's causing the error, and not necessarily the series itself.

**Comment by t0815** [comment]
ah ok...

```
[2024-09-14 16:52:38.780 +02:00] [WRN] [20] Shokofin.API.ShokoAPIClient: Got an unexpected exception for key: "apiKey=default,method=GET,url=/api/v3/Series/496?includeDataFrom=AniDB,TvDB,object"
Shokofin.API.Models.ApiException: InternalServerErrorException
   at Shokofin.API.ShokoAPIClient.<>c__DisplayClass19_0`1.<<Get>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Shokofin.Utils.GuardedMemoryCache.GetOrCreateAsync[TItem](Object key, Action`1 foundAction, Func`1 createFactory, MemoryCacheEntryOptions createOptions)
[2024-09-14 16:52:38.788 +02:00] [ERR] [20] Shokofin.Resolvers.ShokoIgnoreRule: Threw unexpectedly; "InternalServerErrorException"
Shokofin.API.Models.ApiException: InternalServerErrorException
   at Shokofin.API.ShokoAPIClient.<>c__DisplayClass19_0`1.<<Get>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Shokofin.Utils.GuardedMemoryCache.GetOrCreateAsync[TItem](Object key, Action`1 foundAction, Func`1 createFactory, MemoryCacheEntryOptions createOptions)
   at Shokofin.API.ShokoAPIClient.Get[ReturnType](String url, HttpMethod method, String apiKey, Boolean skipCache)
   at Shokofin.API.ShokoAPIManager.GetSeriesIdsForSeason(String seriesId)
   at Shokofin.API.ShokoAPIManager.GetSeriesIdForPath(String path)
   at Shokofin.API.ShokoAPIManager.GetSeasonInfoByPath(String path)
   at Shokofin.Resolvers.ShokoIgnoreRule.ShouldFilterDirectory(String partialPath, String fullPath, Nullable`1 collectionType, Boolean shouldIgnore)
   at Shokofin.Resolvers.ShokoIgnoreRule.ShouldFilterItem(Folder parent, FileSystemMetadata fileInfo)
[2024-09-14 16:52:38.792 +02:00] [ERR] [16] MediaBrowser.Controller.Entities.BaseItem: Error retrieving children
Shokofin.API.Models.ApiException: InternalServerErrorException
   at Shokofin.API.ShokoAPIClient.<>c__DisplayClass19_0`1.<<Get>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Shokofin.Utils.GuardedMemoryCache.GetOrCreateAsync[TItem](Object key, Action`1 foundAction, Func`1 createFactory, MemoryCacheEntryOptions createOptions)
   at Shokofin.API.ShokoAPIClient.Get[ReturnType](String url, HttpMethod method, String apiKey, Boolean skipCache)
   at Shokofin.API.ShokoAPIManager.GetSeriesIdsForSeason(String seriesId)
   at Shokofin.API.ShokoAPIManager.GetSeriesIdForPath(String path)
   at Shokofin.API.ShokoAPIManager.GetSeasonInfoByPath(String path)
   at Shokofin.Resolvers.ShokoIgnoreRule.ShouldFilterDirectory(String partialPath, String fullPath, Nullable`1 collectionType, Boolean shouldIgnore)
   at Shokofin.Resolvers.ShokoIgnoreRule.ShouldFilterItem(Folder parent, FileSystemMetadata fileInfo)
   at Shokofin.Resolvers.ShokoIgnoreRule.MediaBrowser.Controller.Resolvers.IResolverIgnoreRule.ShouldIgnore(FileSystemMetadata fileInfo, BaseItem parent)
   at Emby.Server.Implementations.Library.LibraryManager.<>c__DisplayClass83_0.<IgnoreFile>b__0(IResolverIgnoreRule r)
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Emby.Server.Implementations.Library.LibraryManager.IgnoreFile(FileSystemMetadata file, BaseItem parent)
   at Emby.Server.Implementations.Library.LibraryManager.<>c__DisplayClass87_0.<ResolvePaths>b__0(FileSystemMetadata i)
   at System.Linq.Enumerable.WhereArrayIterator`1.ToList()
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePaths(IEnumerable`1 files, IDirectoryService directoryService, Folder parent, LibraryOptions libraryOptions, Nullable`1 collectionType, IItemResolver[] resolvers)
   at Emby.Server.Implementations.Library.LibraryManager.ResolvePaths(IEnumerable`1 files, IDirectoryService directoryService, Folder parent, LibraryOptions libraryOptions, Nullable`1 collectionType)
   at MediaBrowser.Controller.Entities.Folder.GetNonCachedChildren(IDirectoryService directoryService)
   at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
```

**Comment by t0815** [comment]
series failed was:
https://anidb.net/anime/8315

ill check shoko now... and unlink tvdb

**Comment by t0815** [comment]
aha... it does not have a tvdb link, buuut, i manually linked the file. So that might be the issue....

**Comment by revam** [comment]
@t0815 also check the prequels/sequels

**Comment by revam** [comment]
just to be sure, but are you using the **EXPERIMENTAL** season merging setting?

(asking because otherwise it wouldn't had thrown where it throws, since the path it's throwing at is locked behind that setting)

**Comment by t0815** [comment]
its disabled:

![grafik](https://github.com/user-attachments/assets/cd2dc563-5220-45e2-bb17-33286256d1af)

**Comment by revam** [comment]
> ah ok...
> 
> ```
> [2024-09-14 16:52:38.780 +02:00] [WRN] [20] Shokofin.API.ShokoAPIClient: Got an unexpected exception for key: "apiKey=default,method=GET,url=/api/v3/Series/496?includeDataFrom=AniDB,TvDB,object"
> Shokofin.API.Models.ApiException: InternalServerErrorException
>    at Shokofin.API.ShokoAPIClient.<>c__DisplayClass19_0`1.<<Get>b__1>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Shokofin.Utils.GuardedMemoryCache.GetOrCreateAsync[TItem](Object key, Action`1 foundAction, Func`1 createFactory, MemoryCacheEntryOptions createOptions)
> [2024-09-14 16:52:38.788 +02:00] [ERR] [20] Shokofin.Resolvers.ShokoIgnoreRule: Threw unexpectedly; "InternalServerErrorException"
> Shokofin.API.Models.ApiException: InternalServerErrorException
>    at Shokofin.API.ShokoAPIClient.<>c__DisplayClass19_0`1.<<Get>b__1>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Shokofin.Utils.GuardedMemoryCache.GetOrCreateAsync[TItem](Object key, Action`1 foundAction, Func`1 createFactory, MemoryCacheEntryOptions createOptions)
>    at Shokofin.API.ShokoAPIClient.Get[ReturnType](String url, HttpMethod method, String apiKey, Boolean skipCache)
>    at Shokofin.API.ShokoAPIManager.GetSeriesIdsForSeason(String seriesId)
>    at Shokofin.API.ShokoAPIManager.GetSeriesIdForPath(String path)
>    at Shokofin.API.ShokoAPIManager.GetSeasonInfoByPath(String path)
>    at Shokofin.Resolvers.ShokoIgnoreRule.ShouldFilterDirectory(String partialPath, String fullPath, Nullable`1 collectionType, Boolean shouldIgnore)
>    at Shokofin.Resolvers.ShokoIgnoreRule.ShouldFilterItem(Folder parent, FileSystemMetadata fileInfo)
> [2024-09-14 16:52:38.792 +02:00] [ERR] [16] MediaBrowser.Controller.Entities.BaseItem: Error retrieving children
> Shokofin.API.Models.ApiException: InternalServerErrorException
>    at Shokofin.API.ShokoAPIClient.<>c__DisplayClass19_0`1.<<Get>b__1>d.MoveNext()
> --- End of stack trace from previous location ---
>    at Shokofin.Utils.GuardedMemoryCache.GetOrCreateAsync[TItem](Object key, Action`1 foundAction, Func`1 createFactory, MemoryCacheEntryOptions createOptions)
>    at Shokofin.API.ShokoAPIClient.Get[ReturnType](String url, HttpMethod method, String apiKey, Boolean skipCache)
>    at Shokofin.API.ShokoAPIManager.GetSeriesIdsForSeason(String seriesId)
>    at Shokofin.API.ShokoAPIManager.GetSeriesIdForPath(String path)
>    at Shokofin.API.ShokoAPIManager.GetSeasonInfoByPath(String path)
>    at Shokofin.Resolvers.ShokoIgnoreRule.ShouldFilterDirectory(String partialPath, String fullPath, Nullable`1 collectionType, Boolean shouldIgnore)
>    at Shokofin.Resolvers.ShokoIgnoreRule.ShouldFilterItem(Folder parent, FileSystemMetadata fileInfo)
>    at Shokofin.Resolvers.ShokoIgnoreRule.MediaBrowser.Controller.Resolvers.IResolverIgnoreRule.ShouldIgnore(FileSystemMetadata fileInfo, BaseItem parent)
>    at Emby.Server.Implementations.Library.LibraryManager.<>c__DisplayClass83_0.<IgnoreFile>b__0(IResolverIgnoreRule r)
>    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
>    at Emby.Server.Implementations.Library.LibraryManager.IgnoreFile(FileSystemMetadata file, BaseItem parent)
>    at Emby.Server.Implementations.Library.LibraryManager.<>c__DisplayClass87_0.<ResolvePaths>b__0(FileSystemMetadata i)
>    at System.Linq.Enumerable.WhereArrayIterator`1.ToList()
>    at Emby.Server.Implementations.Library.LibraryManager.ResolvePaths(IEnumerable`1 files, IDirectoryService directoryService, Folder parent, LibraryOptions libraryOptions, Nullable`1 collectionType, IItemResolver[] resolvers)
>    at Emby.Server.Implementations.Library.LibraryManager.ResolvePaths(IEnumerable`1 files, IDirectoryService directoryService, Folder parent, LibraryOptions libraryOptions, Nullable`1 collectionType)
>    at MediaBrowser.Controller.Entities.Folder.GetNonCachedChildren(IDirectoryService directoryService)
>    at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
> ```

nvm, i should had looked at the stack where it threw before asking you to check the prequels/sequels. it is not needed. sorry about that.

**Comment by t0815** [comment]
no problem 😁

**Comment by revam** [comment]
> series failed was: https://anidb.net/anime/8315
> 
> ill check shoko now... and unlink tvdb

that is indeed odd. though there is not much i can do for the _current_ stable release of the server if either a) refreshing the tvdb data doesn't magically make a series link appear or b) removing any potential tvdb ids using either Shoko Desktop or swagger (http://<shoko host>:8111/swagger) doesn't fix it.

**Comment by revam** [comment]
if you know how to inspect the db directly (or so I'm assuming based on the convo so far) then can you check if the CrossRef_AniDB_TvDB table contains the anidb anime id 8315 at all?

**Comment by t0815** [comment]
kk will check

**Comment by t0815** [comment]
crossref_anidb_tvdb
---
| CrossRef_AniDB_TvDBID | AniDBID | TvDBID | CrossRefSource | 
| ---: | ---: | ---: | ---: | 
| 1880 | 8315 | 132251 | 2 | 


but, the id does not seem to match GYO lol... 
I will delete the row manually in db and see what happens.

**Comment by t0815** [comment]
ok, deleting the invalid crossref didnt fix it. But I fixed it, by deleting my manual LINK to the file. 

As a result, I found an other unhandled exception lol... i made new issue 🤣

**Comment by revam** [comment]
so is this server side tvdb issue fixed? or is it still persisting?

**Comment by t0815** [comment]
lol, ok... when i removed the link, it worked. After running import now again (because of the other issue), the file got recognized by scan, and re-added to the movie. Now, this error occurs again.

tvdb links have been removed. 

![grafik](https://github.com/user-attachments/assets/abfb9b0f-8448-4530-a5d6-30e00a5f1039)


Could try to delete whole series... maybe some data is broken... idk...

**Comment by revam** [comment]
TvDB is 100% gone in Shoko Server 5.1. So not applicable anymore.
