### ISSUE TITLE
System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/lib/jellyfin/Shokofin/VFS/{GUID}'

### ISSUE THREAD

**Issue by zerodog137** [ShokoAnime/Shokofin#76]
### Jellyfin version.

10.0.11

### Shokofin version.

4.2.0.3 dev

### Shoko Server version, release channel, and commit hash.

5.0.0 dev (1c392eb)

### File structure of your _Media Library Folder in Jellyfin_/_Import Folder in Shoko Server_.

"Anime A/Episode 1.mkv"
etc...

### Screenshot of the "library settings" section of the plugin settings.

I can't find the "library settings" section, please clarify.

### Library Type(s).

Shows

### Do the issue persists after creating a library with Shoko set as the only metadata provider? (Now is your time to check if you haven't already.)

- [X] Yes, I hereby confirm that the issue persists after creating a library with Shoko set as the only metadata provider.

### Issue

Installed Jellyfin and Shokofin plugin on an almost-fresh Arch Linux install, Shoko Server on a Windows Server install.
Started services, ran Shoko through library, configured Jellyfin and Shokofin. Whenever I refresh my library, I get the attached stack trace, and none of the shows in my Library show up. If I use any other metadata providers, they do show up and some fetch metadata.

I can also reproduce the issue on Windows Server 2k22 (with Shoko running on it), also with stable Shoko and Shokofin. Not sure what I missed, if anything.

### Stack Trace

```log
Oct 17 14:08:53 arch jellyfin[6074]: [14:08:53] [INF] Startup complete 0:00:18.0186175
Oct 17 14:10:12 arch jellyfin[6074]: [14:10:12] [INF] WS 192.168.1.52 request
Oct 17 14:10:53 arch jellyfin[6074]: [14:10:53] [INF] Connected to Shoko Server.
Oct 17 14:11:15 arch jellyfin[6074]: [14:11:15] [INF] Created 0 (0,0), fixed 0 (0,0), skipped 0 (0,0), and removed 0 (0,0,0) entries in folder at /var/lib/jellyfin/Shokofin/VFS/f137a2dd-21bb-c1b9-9aa5-c0f6bf02a805 in 00:00:01>
Oct 17 14:11:15 arch jellyfin[6074]: [14:11:15] [ERR] Threw unexpectedly; Could not find a part of the path '/var/lib/jellyfin/Shokofin/VFS/f137a2dd-21bb-c1b9-9aa5-c0f6bf02a805'.
Oct 17 14:11:15 arch jellyfin[6074]: System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/lib/jellyfin/Shokofin/VFS/f137a2dd-21bb-c1b9-9aa5-c0f6bf02a805'.
Oct 17 14:11:15 arch jellyfin[6074]:    at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
Oct 17 14:11:15 arch jellyfin[6074]:    at System.IO.Enumeration.FileSystemEnumerator`1.Init()
Oct 17 14:11:15 arch jellyfin[6074]:    at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
Oct 17 14:11:15 arch jellyfin[6074]:    at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
Oct 17 14:11:15 arch jellyfin[6074]:    at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
Oct 17 14:11:15 arch jellyfin[6074]:    at System.IO.DirectoryInfo.EnumerateDirectories(String searchPattern, EnumerationOptions enumerationOptions)
Oct 17 14:11:15 arch jellyfin[6074]:    at Emby.Server.Implementations.IO.ManagedFileSystem.GetDirectories(String path, Boolean recursive)
Oct 17 14:11:15 arch jellyfin[6074]:    at Shokofin.Resolvers.ShokoResolver.ResolveMultiple(Folder parent, Nullable`1 collectionType, List`1 fileInfoList)
Oct 17 14:11:15 arch jellyfin[6074]: [14:11:15] [ERR] Error retrieving children from file system
Oct 17 14:11:15 arch jellyfin[6074]: System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/lib/jellyfin/Shokofin/VFS/f137a2dd-21bb-c1b9-9aa5-c0f6bf02a805'.
Oct 17 14:11:15 arch jellyfin[6074]:    at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
Oct 17 14:11:15 arch jellyfin[6074]:    at System.IO.Enumeration.FileSystemEnumerator`1.Init()
Oct 17 14:11:15 arch jellyfin[6074]:    at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
Oct 17 14:11:15 arch jellyfin[6074]:    at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
Oct 17 14:11:15 arch jellyfin[6074]:    at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
Oct 17 14:11:15 arch jellyfin[6074]:    at System.IO.DirectoryInfo.EnumerateDirectories(String searchPattern, EnumerationOptions enumerationOptions)
Oct 17 14:11:15 arch jellyfin[6074]:    at Emby.Server.Implementations.IO.ManagedFileSystem.GetDirectories(String path, Boolean recursive)
Oct 17 14:11:15 arch jellyfin[6074]:    at Shokofin.Resolvers.ShokoResolver.ResolveMultiple(Folder parent, Nullable`1 collectionType, List`1 fileInfoList)
Oct 17 14:11:15 arch jellyfin[6074]:    at Shokofin.Resolvers.ShokoResolver.MediaBrowser.Controller.Resolvers.IMultiItemResolver.ResolveMultiple(Folder parent, List`1 files, Nullable`1 collectionType, IDirectoryService direct>
Oct 17 14:11:15 arch jellyfin[6074]:    at Emby.Server.Implementations.Library.LibraryManager.ResolvePaths(IEnumerable`1 files, IDirectoryService directoryService, Folder parent, LibraryOptions libraryOptions, Nullable`1 coll>
Oct 17 14:11:15 arch jellyfin[6074]:    at Emby.Server.Implementations.Library.LibraryManager.ResolvePaths(IEnumerable`1 files, IDirectoryService directoryService, Folder parent, LibraryOptions libraryOptions, Nullable`1 coll>
Oct 17 14:11:15 arch jellyfin[6074]:    at MediaBrowser.Controller.Entities.Folder.GetNonCachedChildren(IDirectoryService directoryService)
Oct 17 14:11:15 arch jellyfin[6074]:    at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptio>
Oct 17 14:11:21 arch jellyfin[6074]: [14:11:21] [ERR] Threw unexpectedly; Could not find a part of the path '/var/lib/jellyfin/Shokofin/VFS/f137a2dd-21bb-c1b9-9aa5-c0f6bf02a805'.
Oct 17 14:11:21 arch jellyfin[6074]: System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/lib/jellyfin/Shokofin/VFS/f137a2dd-21bb-c1b9-9aa5-c0f6bf02a805'.
Oct 17 14:11:21 arch jellyfin[6074]:    at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
Oct 17 14:11:21 arch jellyfin[6074]:    at System.IO.Enumeration.FileSystemEnumerator`1.Init()
Oct 17 14:11:21 arch jellyfin[6074]:    at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
Oct 17 14:11:21 arch jellyfin[6074]:    at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
Oct 17 14:11:21 arch jellyfin[6074]:    at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
Oct 17 14:11:21 arch jellyfin[6074]:    at System.IO.DirectoryInfo.EnumerateDirectories(String searchPattern, EnumerationOptions enumerationOptions)
Oct 17 14:11:21 arch jellyfin[6074]:    at Emby.Server.Implementations.IO.ManagedFileSystem.GetDirectories(String path, Boolean recursive)
Oct 17 14:11:21 arch jellyfin[6074]:    at Shokofin.Resolvers.ShokoResolver.ResolveMultiple(Folder parent, Nullable`1 collectionType, List`1 fileInfoList)
Oct 17 14:11:21 arch jellyfin[6074]: [14:11:21] [ERR] Error retrieving children from file system
Oct 17 14:11:21 arch jellyfin[6074]: System.IO.DirectoryNotFoundException: Could not find a part of the path '/var/lib/jellyfin/Shokofin/VFS/f137a2dd-21bb-c1b9-9aa5-c0f6bf02a805'.
Oct 17 14:11:21 arch jellyfin[6074]:    at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
Oct 17 14:11:21 arch jellyfin[6074]:    at System.IO.Enumeration.FileSystemEnumerator`1.Init()
Oct 17 14:11:21 arch jellyfin[6074]:    at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
Oct 17 14:11:21 arch jellyfin[6074]:    at System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
Oct 17 14:11:21 arch jellyfin[6074]:    at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
Oct 17 14:11:21 arch jellyfin[6074]:    at System.IO.DirectoryInfo.EnumerateDirectories(String searchPattern, EnumerationOptions enumerationOptions)
Oct 17 14:11:21 arch jellyfin[6074]:    at Emby.Server.Implementations.IO.ManagedFileSystem.GetDirectories(String path, Boolean recursive)
Oct 17 14:11:21 arch jellyfin[6074]:    at Shokofin.Resolvers.ShokoResolver.ResolveMultiple(Folder parent, Nullable`1 collectionType, List`1 fileInfoList)
```

**Comment by zerodog137** [comment]
As for my library settings (sorry I just woke up), not sure how to take a screenshot of the whole panel without taking multiple.
Everything there is set as default with my _nfs share_ as folder, except for the metadata providers - only have Shoko there.

**Comment by zerodog137** [comment]
#58 
I searched for VFS in GitHub issues but somehow missed that one.
Tried reinstalling Shoko Server, but it's not importing any anidb data now. I might be banned (API only)? The logs just report that some anidb-related task was scheduled but nothing else of it. Bit of a mess, I'll wait some time to see if Shoko works later.

**Comment by revam** [comment]
this exact error is fixed in https://github.com/ShokoAnime/Shokofin/commit/b0cc8d4194188644fabb7b4ef7c6eb1474c353a1

**Comment by revam** [comment]
or wait, it threw further down the path. will fix that too.

**Comment by revam** [comment]
same issue, different place
