### ISSUE TITLE
Error when trying to create a library

### ISSUE THREAD

**Issue by DestinyofYeet** [ShokoAnime/Shokofin#82]
### Jellyfin version.

10.10.3

### Shokofin version.

5.0.0

### Shoko Server version, release channel, and commit hash.

Version 4.2.2.0 (Stable, 7d4f476)

### File structure of your _Media Library Folder in Jellyfin_/_Import Folder in Shoko Server_.

```
/mnt/data/data/media/jellyfin/animes
| - xxx
|  | - Season 01
|        | - Episode 01
```

### Screenshot of the "library settings" section of the plugin settings.

![image](https://github.com/user-attachments/assets/0443e8da-328d-41c0-af74-f87e35741084)
![image](https://github.com/user-attachments/assets/bc9be0e1-39db-4cf3-931e-a656904e3054)

### Library Type(s).

Shows

### Do the issue persists after creating a library with Shoko set as the only metadata provider? (Now is your time to check if you haven't already.)

- [X] Yes, I hereby confirm that the issue persists after creating a library with Shoko set as the only metadata provider.

### Issue

When trying to scan a newly created library according to the Shokofin documentation, the following occurs:
- The Scan completes instantly
- No Animes are found (although there are some in the media folder)
- The Stack Trace is generated in jellyfin logs.

### Stack Trace

```
Dez 05 20:33:06 nix-server jellyfin[990039]: [20:33:06] [WRN] [38] Shokofin.API.ShokoAPIClient: Got an unexpected exception for key: apiKey=default,method=GET,url=/api/v3/Series/1/File?pageSize=0&include=XRefs&includeDataFrom=AniDB,object
Dez 05 20:33:06 nix-server jellyfin[990039]: System.Text.Json.JsonException: The JSON value could not be converted to Shokofin.API.Models.ListResult`1[Shokofin.API.Models.File]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.API.ShokoAPIClient.<>c__DisplayClass9_0`1.<<Get>b__1>d.MoveNext()
Dez 05 20:33:06 nix-server jellyfin[990039]: --- End of stack trace from previous location ---
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.Utils.GuardedMemoryCache.GetOrCreateAsync[TItem](Object key, Action`1 foundAction, Func`1 createFactory, MemoryCacheEntryOptions createOptions)
Dez 05 20:33:06 nix-server jellyfin[990039]: [20:33:06] [WRN] [38] Shokofin.API.ShokoAPIManager: Got an unexpected exception for key: series-path-set-and-episode-ids:$1
Dez 05 20:33:06 nix-server jellyfin[990039]: System.Text.Json.JsonException: The JSON value could not be converted to Shokofin.API.Models.ListResult`1[Shokofin.API.Models.File]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.API.ShokoAPIClient.<>c__DisplayClass9_0`1.<<Get>b__1>d.MoveNext()
Dez 05 20:33:06 nix-server jellyfin[990039]: --- End of stack trace from previous location ---
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.Utils.GuardedMemoryCache.GetOrCreateAsync[TItem](Object key, Action`1 foundAction, Func`1 createFactory, MemoryCacheEntryOptions createOptions)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.API.ShokoAPIClient.Get[ReturnType](String url, HttpMethod method, String apiKey, Boolean skipCache)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.API.ShokoAPIClient.GetFilesForSeries(String seriesId)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.API.ShokoAPIManager.<>c__DisplayClass32_0.<<GetPathSetAndLocalEpisodeIdsForSeries>b__0>d.MoveNext()
Dez 05 20:33:06 nix-server jellyfin[990039]: --- End of stack trace from previous location ---
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.Utils.GuardedMemoryCache.GetOrCreateAsync[TItem](Object key, Func`1 createFactory, MemoryCacheEntryOptions createOptions)
Dez 05 20:33:06 nix-server jellyfin[990039]: [20:33:06] [ERR] [38] Shokofin.Resolvers.ShokoIgnoreRule: Threw unexpectedly; The JSON value could not be converted to Shokofin.API.Models.ListResult`1[Shokofin.API.Models.File]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
Dez 05 20:33:06 nix-server jellyfin[990039]: System.Text.Json.JsonException: The JSON value could not be converted to Shokofin.API.Models.ListResult`1[Shokofin.API.Models.File]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.API.ShokoAPIClient.<>c__DisplayClass9_0`1.<<Get>b__1>d.MoveNext()
Dez 05 20:33:06 nix-server jellyfin[990039]: --- End of stack trace from previous location ---
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.Utils.GuardedMemoryCache.GetOrCreateAsync[TItem](Object key, Action`1 foundAction, Func`1 createFactory, MemoryCacheEntryOptions createOptions)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.API.ShokoAPIClient.Get[ReturnType](String url, HttpMethod method, String apiKey, Boolean skipCache)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.API.ShokoAPIClient.GetFilesForSeries(String seriesId)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.API.ShokoAPIManager.<>c__DisplayClass32_0.<<GetPathSetAndLocalEpisodeIdsForSeries>b__0>d.MoveNext()
Dez 05 20:33:06 nix-server jellyfin[990039]: --- End of stack trace from previous location ---
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.Utils.GuardedMemoryCache.GetOrCreateAsync[TItem](Object key, Func`1 createFactory, MemoryCacheEntryOptions createOptions)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.API.ShokoAPIManager.GetPathSetForSeries(String seriesId, IEnumerable`1 extraIds)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.API.ShokoAPIManager.GetSeriesIdForPath(String path)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.API.ShokoAPIManager.GetSeasonInfoByPath(String path)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.Resolvers.ShokoIgnoreRule.ShouldFilterDirectory(String partialPath, String fullPath, Nullable`1 collectionType, Boolean shouldIgnore)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.Resolvers.ShokoIgnoreRule.ShouldFilterItem(Folder parent, FileSystemMetadata fileInfo)
Dez 05 20:33:06 nix-server jellyfin[990039]: [20:33:06] [ERR] [33] MediaBrowser.Controller.Entities.BaseItem: Error retrieving children
Dez 05 20:33:06 nix-server jellyfin[990039]: System.Text.Json.JsonException: The JSON value could not be converted to Shokofin.API.Models.ListResult`1[Shokofin.API.Models.File]. Path: $ | LineNumber: 0 | BytePositionInLine: 1.
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.DeserializeAsync(Stream utf8Json, CancellationToken cancellationToken)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.API.ShokoAPIClient.<>c__DisplayClass9_0`1.<<Get>b__1>d.MoveNext()
Dez 05 20:33:06 nix-server jellyfin[990039]: --- End of stack trace from previous location ---
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.Utils.GuardedMemoryCache.GetOrCreateAsync[TItem](Object key, Action`1 foundAction, Func`1 createFactory, MemoryCacheEntryOptions createOptions)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.API.ShokoAPIClient.Get[ReturnType](String url, HttpMethod method, String apiKey, Boolean skipCache)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.API.ShokoAPIClient.GetFilesForSeries(String seriesId)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.API.ShokoAPIManager.<>c__DisplayClass32_0.<<GetPathSetAndLocalEpisodeIdsForSeries>b__0>d.MoveNext()
Dez 05 20:33:06 nix-server jellyfin[990039]: --- End of stack trace from previous location ---
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.Utils.GuardedMemoryCache.GetOrCreateAsync[TItem](Object key, Func`1 createFactory, MemoryCacheEntryOptions createOptions)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.API.ShokoAPIManager.GetPathSetForSeries(String seriesId, IEnumerable`1 extraIds)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.API.ShokoAPIManager.GetSeriesIdForPath(String path)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.API.ShokoAPIManager.GetSeasonInfoByPath(String path)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.Resolvers.ShokoIgnoreRule.ShouldFilterDirectory(String partialPath, String fullPath, Nullable`1 collectionType, Boolean shouldIgnore)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.Resolvers.ShokoIgnoreRule.ShouldFilterItem(Folder parent, FileSystemMetadata fileInfo)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Shokofin.Resolvers.ShokoIgnoreRule.MediaBrowser.Controller.Resolvers.IResolverIgnoreRule.ShouldIgnore(FileSystemMetadata fileInfo, BaseItem parent)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
Dez 05 20:33:06 nix-server jellyfin[990039]:    at System.Linq.Enumerable.WhereArrayIterator`1.ToList()
Dez 05 20:33:06 nix-server jellyfin[990039]:    at Emby.Server.Implementations.Library.LibraryManager.ResolvePaths(IEnumerable`1 files, IDirectoryService directoryService, Folder parent, LibraryOptions libraryOptions, Nullable`1 collectionType, IItemResolver[] resolvers) in /build/source/Emby.Server.Implementations/Library/LibraryManager.cs:line 668
Dez 05 20:33:06 nix-server jellyfin[990039]:    at MediaBrowser.Controller.Entities.Folder.GetNonCachedChildren(IDirectoryService directoryService) in /build/source/MediaBrowser.Controller/Entities/Folder.cs:line 652
Dez 05 20:33:06 nix-server jellyfin[990039]:    at MediaBrowser.Controller.Entities.Folder.ValidateChildrenInternal2(IProgress`1 progress, Boolean recursive, Boolean refreshChildMetadata, Boolean allowRemoveRoot, MetadataRefreshOptions refreshOptions, IDirectoryService directoryService, CancellationToken cancellationToken)
```

**Comment by DestinyofYeet** [comment]
I have disabled the VFS as seen in the screenshot, so I can use jellyfin again. The VFS option was enabled at the time of the stack.

A re-install of jellyfin did not help.

**Comment by revam** [comment]
Update your Shoko Server to 5.0.0.0 or downgrade the plugin to 4.2.2.0 and Jellyfin to 10.9.11. And next time, refer to [the version matrix in the read-me file](https://github.com/ShokoAnime/Shokofin?tab=readme-ov-file#install) or [the version matrix in our docs](https://docs.shokoanime.com/jellyfin/installing-shokofin#taking-the-first-step) for which versions are compatible with each other.

**Comment by DestinyofYeet** [comment]
:facepalm: thanks
