### ISSUE TITLE
Error "path gave a file that doesn't have a matching file location"

### ISSUE THREAD

**Issue by tgxiii** [ShokoAnime/Shokofin#83]
### Jellyfin version.

10.10.13

### Shokofin version.

5.0.0.0

### Shoko Server version, release channel, and commit hash.

Version 5.0.0.92 (Dev, 5a1bc7f)

### File structure of your _Media Library Folder in Jellyfin_/_Import Folder in Shoko Server_.

/data/anime/{Collection|Favorites}/{Series Name}/{various file names}.{extension}

### Screenshot of the "library settings" section of the plugin settings.

![image](https://github.com/user-attachments/assets/fa461121-09d1-4d3a-8590-e1f21741b833)
![image](https://github.com/user-attachments/assets/547f5889-af97-4337-97a6-844cb536b8bf)

![image](https://github.com/user-attachments/assets/282e1991-3561-46c4-abfa-c9008b629830)
![image](https://github.com/user-attachments/assets/621a0dbd-5d3b-4c49-a033-bca331a3fc83)
![image](https://github.com/user-attachments/assets/3fd8ef6d-cc31-4828-97df-657aafae7246)
![image](https://github.com/user-attachments/assets/a0591d48-8399-4a2d-b8bc-15f5892b4ec2)
![image](https://github.com/user-attachments/assets/ba0171d4-5058-465a-9b48-a3da0e92af6f)
![image](https://github.com/user-attachments/assets/dd56ef65-501b-44ea-b27c-7e609ea6b3ed)
![image](https://github.com/user-attachments/assets/60992608-3b74-4a27-a123-2572bf2d72bd)

### Library Type(s).

Shows

### Do the issue persists after creating a library with Shoko set as the only metadata provider? (Now is your time to check if you haven't already.)

- [X] Yes, I hereby confirm that the issue persists after creating a library with Shoko set as the only metadata provider.

### Issue

Getting this error for what seems like every file:

```
[2024-12-19 21:52:35.525 -08:00] [ERR] [65] Shokofin.Providers.EpisodeProvider: Threw unexpectedly while refreshing "/data/anime/Favorites/Bleach/[DB] Bleach - 175- The Revenging Assassin, Ichigo i… [90E0D98E].avi": False
System.Exception: I have no idea how this happened, but the path gave a file that doesn't have a matching file location. See you in #support. (File=8038)
   at Shokofin.API.ShokoAPIManager.GetFileInfoByPath(String path)
   at Shokofin.Providers.EpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
[2024-12-19 21:52:35.526 -08:00] [ERR] [65] Shokofin.Providers.ImageProvider: Threw unexpectedly for Episode "Bleach - 175- The Revenging Assassin, Ichigo i…"; "I have no idea how this happened, but the path gave a file that doesn't have a matching file location. See you in #support. (File=8038)"
System.Exception: I have no idea how this happened, but the path gave a file that doesn't have a matching file location. See you in #support. (File=8038)
   at Shokofin.API.ShokoAPIManager.GetFileInfoByPath(String path)
   at Shokofin.API.ShokoAPIManager.TryGetEpisodeIdsForPath(String path, List`1& episodeIds)
   at Shokofin.API.ShokoAPIManager.TryGetEpisodeIdForPath(String path, String& episodeId)
   at Shokofin.IdLookup.TryGetEpisodeIdFor(String path, String& episodeId)
   at Shokofin.IdLookup.TryGetEpisodeIdFor(BaseItem item, String& episodeId)
   at Shokofin.Providers.ImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
```

**Comment by revam** [comment]
Pretty sure this is GitHub and not #support on our Discord, but here goes.

Can you send the API response for the file with id 8038? You can use curl or swagger. We have a guide for how to use swagger to auth and send requests (to reset the web ui) in our Discord, but I'm not going to send that here since I'm writing this on mobile rn.

If my suspicious is correct then it's because of path mappings being different for the '…' symbol (not three '.'s) between the Jellyfin host and Shoko Server host, making it so it can't be recognised, but confirming what the Shoko APIv3 returns will clarify if it is or not.

**Comment by tgxiii** [comment]
I tried joining Discord but got this:

![image](https://github.com/user-attachments/assets/b06fcfed-09dd-4f22-b42e-9296daa95d27)


Here's the response:

```
{
  "ID": 8038,
  "Size": 178258198,
  "IsVariation": false,
  "Hashes": {
    "ED2K": "CA74CF7CEE7158AC31106A0FCE7D1C27",
    "SHA1": "7BBF15E3C999B96BF97C257D574B3B2091F8618D",
    "CRC32": "90E0D98E",
    "MD5": "E3A0FECE0AC34D8A69C20C1CE754A96E"
  },
  "Locations": [
    {
      "ID": 8038,
      "FileID": 8038,
      "ImportFolderID": 1,
      "RelativePath": "Bleach/[DB] Bleach - 175- The Revenging Assassin, Ichigo i… [90E0D98E].avi",
      "IsAccessible": true
    }
  ],
  "AVDump": {
    "Status": null,
    "LastDumpedAt": null,
    "LastVersion": null
  },
  "Resolution": "480p",
  "Duration": "00:24:01.9910000",
  "ResumePosition": null,
  "Viewed": null,
  "Watched": null,
  "Imported": "2024-12-11T07:55:35.2865206Z",
  "Created": "2024-12-11T06:20:46.2933772Z",
  "Updated": "2024-12-11T06:20:48.4894209Z"
}
```

This is the file in the Shoko Server container:

```
root@51239bc9b237:/usr/src/app/build# ls -l /data/anime/Favorites/Bleach | grep 175-
-rwxrwxrwx 1 shoko users 178258198 Jul  4  2008 [DB] Bleach - 175- The Revenging Assassin, Ichigo i… [90E0D98E].avi
```

This is the file in Jellyfin in Ubuntu:

```
root@jellyfin:~# ls -l /data/anime/Favorites/Bleach | grep 175-
-rwxr-xr-x 1 root root 178258198 Jul  4  2008 [DB] Bleach - 175- The Revenging Assassin, Ichigo i… [90E0D98E].avi
```

------------------

Here's one example though without the `...`:

```
[2024-12-21 21:40:56.457 -08:00] [INF] [56] Shokofin.Providers.ImageProvider: Getting 1 images for season 3 in "Full Metal Alchemist" (Series="1",Language="en")
[2024-12-21 21:40:57.655 -08:00] [INF] [68] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/anime/Favorites/Hagane no Renkinjutsushi (2009)/[Coalgirls] Fullmetal Alchemist- Brotherhood - 16- Footsteps of a Comrade-in-Arms [679B4F44].mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-12-21 21:40:57.987 -08:00] [ERR] [68] Shokofin.Providers.EpisodeProvider: Threw unexpectedly while refreshing "/data/anime/Favorites/Hagane no Renkinjutsushi (2009)/[Coalgirls] Fullmetal Alchemist- Brotherhood - 16- Footsteps of a Comrade-in-Arms [679B4F44].mkv": False
System.Exception: I have no idea how this happened, but the path gave a file that doesn't have a matching file location. See you in #support. (File=1)
   at Shokofin.API.ShokoAPIManager.GetFileInfoByPath(String path)
   at Shokofin.Providers.EpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
[2024-12-21 21:40:57.987 -08:00] [ERR] [68] Shokofin.Providers.ImageProvider: Threw unexpectedly for Episode "Fullmetal Alchemist- Brotherhood - 16- Footsteps of a Comrade-in-Arms"; "I have no idea how this happened, but the path gave a file that doesn't have a matching file location. See you in #support. (File=1)"
System.Exception: I have no idea how this happened, but the path gave a file that doesn't have a matching file location. See you in #support. (File=1)
   at Shokofin.API.ShokoAPIManager.GetFileInfoByPath(String path)
   at Shokofin.API.ShokoAPIManager.TryGetEpisodeIdsForPath(String path, List`1& episodeIds)
   at Shokofin.API.ShokoAPIManager.TryGetEpisodeIdForPath(String path, String& episodeId)
   at Shokofin.IdLookup.TryGetEpisodeIdFor(String path, String& episodeId)
   at Shokofin.IdLookup.TryGetEpisodeIdFor(BaseItem item, String& episodeId)
   at Shokofin.Providers.ImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
[2024-12-21 21:40:58.328 -08:00] [ERR] [68] Shokofin.API.ShokoAPIManager: Encountered an error while trying to lookup the file id for "/data/anime/Favorites/Hagane no Renkinjutsushi (2009)/[Coalgirls] Fullmetal Alchemist- Brotherhood - 16- Footsteps of a Comrade-in-Arms [679B4F44].mkv"
System.Exception: I have no idea how this happened, but the path gave a file that doesn't have a matching file location. See you in #support. (File=1)
   at Shokofin.API.ShokoAPIManager.GetFileInfoByPath(String path)
   at Shokofin.API.ShokoAPIManager.TryGetFileIdForPath(String path, String& fileId)
```

```
{
  "ID": 1,
  "Size": 610439784,
  "IsVariation": false,
  "Hashes": {
    "ED2K": "A2E19EE56AA05C0099F7271B2810C4A7",
    "SHA1": "66061C9C12E53AF483CA65D0D64D2CC0D8FC1521",
    "CRC32": "679B4F44",
    "MD5": "3F9D565AA7B43B90CB27CE0577A648A4"
  },
  "Locations": [
    {
      "ID": 1,
      "FileID": 1,
      "ImportFolderID": 1,
      "RelativePath": "Hagane no Renkinjutsushi (2009)/[Coalgirls] Fullmetal Alchemist- Brotherhood - 16- Footsteps of a Comrade-in-Arms [679B4F44].mkv",
      "IsAccessible": true
    }
  ],
  "AVDump": {
    "Status": null,
    "LastDumpedAt": null,
    "LastVersion": null
  },
  "Resolution": "720p",
  "Duration": "00:24:27.2150000",
  "ResumePosition": null,
  "Viewed": null,
  "Watched": null,
  "Imported": "2024-12-21T05:44:31.306381Z",
  "Created": "2024-12-21T05:44:12.2016511Z",
  "Updated": "2024-12-21T05:44:22.6428143Z"
}
```

**Comment by revam** [comment]
can you also include the cross-references (XRefs) for one of the files?

**Comment by revam** [comment]
also, which invite link did you use and where did you find it?

try https://discord.gg/shokoanime if you want to join and haven't that link already.

**Comment by tgxiii** [comment]
I used the one on shokoanime.com

I just tried that one that you gave and got this:

![image](https://github.com/user-attachments/assets/1d027f48-a622-4fde-984b-e5f0851e69fc)

**Comment by tgxiii** [comment]
> can you also include the cross-references (XRefs) for one of the files?

Which cross-reference do you need? I could only find Tmdb-related endpoints in Swagger.

**Comment by revam** [comment]
> I used the one on shokoanime.com
> 
> I just tried that one that you gave and got this:

Works fine for me.

> > can you also include the cross-references (XRefs) for one of the files?
> 
> Which cross-reference do you need? I could only find Tmdb-related endpoints in Swagger.

Can you `include` the cross-references (`XRefs`) as a query option when fetching one of the files?

E.g.
`http://<shoko host>:8111/api/v3/File/<file id>?include=XRefs`

**Comment by tgxiii** [comment]
> Works fine for me.

Probably my account or IP. I tried with a different email and got the same thing for both invites.

------------------

Here's the File response with Xrefs:

```
{
  "ID": 1,
  "SeriesIDs": [
    {
      "SeriesID": {
        "ID": 1,
        "AniDB": 6107,
        "TMDB": {
          "Movie": [],
          "Show": []
        }
      },
      "EpisodeIDs": [
        {
          "ID": 23,
          "AniDB": 104977,
          "TMDB": {
            "Episode": [],
            "Movie": [],
            "Show": []
          },
          "ReleaseGroup": 7407,
          "ED2K": "A2E19EE56AA05C0099F7271B2810C4A7",
          "FileSize": 610439784,
          "Percentage": {
            "Start": 0,
            "End": 100,
            "Size": 100,
            "Group": 1
          },
          "Source": "AniDB"
        }
      ]
    }
  ],
  "Size": 610439784,
  "IsVariation": false,
  "Hashes": {
    "ED2K": "A2E19EE56AA05C0099F7271B2810C4A7",
    "SHA1": "66061C9C12E53AF483CA65D0D64D2CC0D8FC1521",
    "CRC32": "679B4F44",
    "MD5": "3F9D565AA7B43B90CB27CE0577A648A4"
  },
  "Locations": [
    {
      "ID": 1,
      "FileID": 1,
      "ImportFolderID": 1,
      "RelativePath": "Hagane no Renkinjutsushi (2009)/[Coalgirls] Fullmetal Alchemist- Brotherhood - 16- Footsteps of a Comrade-in-Arms [679B4F44].mkv",
      "IsAccessible": true
    }
  ],
  "AVDump": {
    "Status": null,
    "LastDumpedAt": null,
    "LastVersion": null
  },
  "Resolution": "720p",
  "Duration": "00:24:27.2150000",
  "ResumePosition": null,
  "Viewed": null,
  "Watched": null,
  "Imported": "2024-12-21T05:44:31.306381Z",
  "Created": "2024-12-21T05:44:12.2016511Z",
  "Updated": "2024-12-21T05:44:22.6428143Z"
}
```

**Comment by revam** [comment]
It seems like you've mounted `/data/anime/` in Jellyfin for the library but mounted `/data/anime/Favorites/` in Shoko, so the relative path is one layer too deep when comparing the paths. Try either switching the mount to `/data/anime/Favorites/` in Jellyfin or switching the mount to `/data/anime/` in Shoko.

Judging by the code block in https://github.com/ShokoAnime/Shokofin/issues/83#issuecomment-2558567608
```log
[2024-12-21 21:40:56.457 -08:00] [INF] [56] Shokofin.Providers.ImageProvider: Getting 1 images for season 3 in "Full Metal Alchemist" (Series="1",Language="en")
[2024-12-21 21:40:57.655 -08:00] [INF] [68] MediaBrowser.MediaEncoding.Encoder.MediaEncoder: Starting "/usr/lib/jellyfin-ffmpeg/ffprobe" with args "-analyzeduration 200M -probesize 1G -i file:\"/data/anime/Favorites/Hagane no Renkinjutsushi (2009)/[Coalgirls] Fullmetal Alchemist- Brotherhood - 16- Footsteps of a Comrade-in-Arms [679B4F44].mkv\" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format"
[2024-12-21 21:40:57.987 -08:00] [ERR] [68] Shokofin.Providers.EpisodeProvider: Threw unexpectedly while refreshing "/data/anime/Favorites/Hagane no Renkinjutsushi (2009)/[Coalgirls] Fullmetal Alchemist- Brotherhood - 16- Footsteps of a Comrade-in-Arms [679B4F44].mkv": False
System.Exception: I have no idea how this happened, but the path gave a file that doesn't have a matching file location. See you in #support. (File=1)
   at Shokofin.API.ShokoAPIManager.GetFileInfoByPath(String path)
   at Shokofin.Providers.EpisodeProvider.GetMetadata(EpisodeInfo info, CancellationToken cancellationToken)
[2024-12-21 21:40:57.987 -08:00] [ERR] [68] Shokofin.Providers.ImageProvider: Threw unexpectedly for Episode "Fullmetal Alchemist- Brotherhood - 16- Footsteps of a Comrade-in-Arms"; "I have no idea how this happened, but the path gave a file that doesn't have a matching file location. See you in #support. (File=1)"
System.Exception: I have no idea how this happened, but the path gave a file that doesn't have a matching file location. See you in #support. (File=1)
   at Shokofin.API.ShokoAPIManager.GetFileInfoByPath(String path)
   at Shokofin.API.ShokoAPIManager.TryGetEpisodeIdsForPath(String path, List`1& episodeIds)
   at Shokofin.API.ShokoAPIManager.TryGetEpisodeIdForPath(String path, String& episodeId)
   at Shokofin.IdLookup.TryGetEpisodeIdFor(String path, String& episodeId)
   at Shokofin.IdLookup.TryGetEpisodeIdFor(BaseItem item, String& episodeId)
   at Shokofin.Providers.ImageProvider.GetImages(BaseItem item, CancellationToken cancellationToken)
[2024-12-21 21:40:58.328 -08:00] [ERR] [68] Shokofin.API.ShokoAPIManager: Encountered an error while trying to lookup the file id for "/data/anime/Favorites/Hagane no Renkinjutsushi (2009)/[Coalgirls] Fullmetal Alchemist- Brotherhood - 16- Footsteps of a Comrade-in-Arms [679B4F44].mkv"
System.Exception: I have no idea how this happened, but the path gave a file that doesn't have a matching file location. See you in #support. (File=1)
   at Shokofin.API.ShokoAPIManager.GetFileInfoByPath(String path)
   at Shokofin.API.ShokoAPIManager.TryGetFileIdForPath(String path, String& fileId)
```

Combined with the screenshot of your media folders assigned to the library in your initial post.

**Comment by revam** [comment]
I'm closing this for now because I haven't gotten a response since january. If you're still having issues with this then feel free to re-open this issue or open a new one.
